# Generated by Django 4.2.30 on 2026-05-15 12:38

from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    OrdemServico = apps.get_model('core', 'OrdemServico')
    PerfilUsuario = apps.get_model('core', 'PerfilUsuario')
    OpcaoPrioridade = apps.get_model('core', 'OpcaoPrioridade')
    OpcaoTipo = apps.get_model('core', 'OpcaoTipo')
    OpcaoCategoria = apps.get_model('core', 'OpcaoCategoria')
    OpcaoUrgencia = apps.get_model('core', 'OpcaoUrgencia')
    OpcaoDepartamento = apps.get_model('core', 'OpcaoDepartamento')

    for os_obj in OrdemServico.objects.all().iterator():
        if os_obj.prioridade and not os_obj.prioridade_fk_id:
            prio, _ = OpcaoPrioridade.objects.get_or_create(
                nome=os_obj.prioridade,
                defaults={'nivel': 1},
            )
            os_obj.prioridade_fk_id = prio.id

        if os_obj.tipo and not os_obj.tipo_fk_id:
            tipo, _ = OpcaoTipo.objects.get_or_create(nome=os_obj.tipo)
            os_obj.tipo_fk_id = tipo.id

        if os_obj.categoria and not os_obj.categoria_fk_id:
            cat, _ = OpcaoCategoria.objects.get_or_create(nome=os_obj.categoria)
            os_obj.categoria_fk_id = cat.id

        if os_obj.urgencia and not os_obj.urgencia_fk_id:
            urg, _ = OpcaoUrgencia.objects.get_or_create(
                nome=os_obj.urgencia,
                defaults={'nivel': 1},
            )
            os_obj.urgencia_fk_id = urg.id

        if os_obj.departamento and not os_obj.departamento_fk_id:
            dep, _ = OpcaoDepartamento.objects.get_or_create(nome=os_obj.departamento)
            os_obj.departamento_fk_id = dep.id

        if (
            os_obj.prioridade_fk_id
            or os_obj.tipo_fk_id
            or os_obj.categoria_fk_id
            or os_obj.urgencia_fk_id
            or os_obj.departamento_fk_id
        ):
            os_obj.save(
                update_fields=[
                    'prioridade_fk',
                    'tipo_fk',
                    'categoria_fk',
                    'urgencia_fk',
                    'departamento_fk',
                ]
            )

    for perfil in PerfilUsuario.objects.all().iterator():
        if perfil.departamento and not perfil.departamento_fk_id:
            dep, _ = OpcaoDepartamento.objects.get_or_create(nome=perfil.departamento)
            perfil.departamento_fk_id = dep.id
            perfil.save(update_fields=['departamento_fk'])


def backwards(apps, schema_editor):
    OrdemServico = apps.get_model('core', 'OrdemServico')
    PerfilUsuario = apps.get_model('core', 'PerfilUsuario')
    for os_obj in OrdemServico.objects.all().iterator():
        changed = False
        if os_obj.prioridade_fk_id and not os_obj.prioridade:
            os_obj.prioridade = os_obj.prioridade_fk.nome
            changed = True
        if os_obj.tipo_fk_id and not os_obj.tipo:
            os_obj.tipo = os_obj.tipo_fk.nome
            changed = True
        if os_obj.categoria_fk_id and not os_obj.categoria:
            os_obj.categoria = os_obj.categoria_fk.nome
            changed = True
        if os_obj.urgencia_fk_id and not os_obj.urgencia:
            os_obj.urgencia = os_obj.urgencia_fk.nome
            changed = True
        if os_obj.departamento_fk_id and not os_obj.departamento:
            os_obj.departamento = os_obj.departamento_fk.nome
            changed = True
        if changed:
            os_obj.save(
                update_fields=['prioridade', 'tipo', 'categoria', 'urgencia', 'departamento']
            )

    for perfil in PerfilUsuario.objects.all().iterator():
        if perfil.departamento_fk_id and not perfil.departamento:
            perfil.departamento = perfil.departamento_fk.nome
            perfil.save(update_fields=['departamento'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='categoria_fk',
            field=models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_categoria', to='core.opcaocategoria'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='departamento_fk',
            field=models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_departamento', to='core.opcaodepartamento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prioridade_fk',
            field=models.ForeignKey(blank=True, db_column='prioridade_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_prioridade', to='core.opcaoprioridade'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_fk',
            field=models.ForeignKey(blank=True, db_column='tipo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_tipo', to='core.opcaotipo'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='urgencia_fk',
            field=models.ForeignKey(blank=True, db_column='urgencia_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_urgencia', to='core.opcaourgencia'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='departamento_fk',
            field=models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='core.opcaodepartamento'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
