# Generated by Django 4.2.30 on 2026-05-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordemservico_categoria_fk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='prioridade',
            new_name='prioridade_old',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='tipo',
            new_name='tipo_old',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='categoria',
            new_name='categoria_old',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='urgencia',
            new_name='urgencia_old',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='departamento',
            new_name='departamento_old',
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='departamento',
            new_name='departamento_old',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='prioridade_fk',
            new_name='prioridade',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='tipo_fk',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='categoria_fk',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='urgencia_fk',
            new_name='urgencia',
        ),
        migrations.RenameField(
            model_name='ordemservico',
            old_name='departamento_fk',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='departamento_fk',
            new_name='departamento',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='prioridade_old',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tipo_old',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='categoria_old',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='urgencia_old',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='departamento_old',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='departamento_old',
        ),
    ]
