# Generated by Django 4.2.30 on 2026-05-15 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ordemservico_categoria_fk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='aguardando_em',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='avaliacao_em',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='em_andamento_em',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='encerrada_em',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='fechada_em',
        ),
    ]
